# Generated by Django 5.2.8 on 2025-11-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Системное имя меню, используется в шаблоне: {% draw_menu 'main_menu' %}", max_length=100, unique=True)),
                ('verbose_name', models.CharField(blank=True, help_text='Человекочитаемое название (для админки).', max_length=255)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('named_url', models.CharField(blank=True, help_text="Имя url из urls.py (reverse). Если указано, поле 'url' игнорируется.", max_length=255)),
                ('url', models.CharField(blank=True, help_text='Явный URL. Используется, если named_url не задан или неразрешим.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('menu', 'parent__id', 'order', 'id'),
            },
        ),
    ]
