# Generated by Django 5.2.8 on 2025-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_create_demo_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='render_as_dropdown',
            field=models.BooleanField(default=False, help_text='Если включено, все пункты меню будут обернуты в родительский dropdown элемент', verbose_name='Отрисовать как dropdown'),
        ),
    ]
