# Generated by Django 5.2.8 on 2025-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_menu_render_as_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dropdown_title',
            field=models.CharField(blank=True, help_text="Текст для родительского элемента (например, 'Profile', 'Account'). Используется только если 'Отрисовать как dropdown' включено", max_length=255, verbose_name='Заголовок dropdown'),
        ),
    ]
